openapi: 3.0.2
info:
  description: "This is a reference for gate-jump's API."
  version: "1.0.0"
  title: "gate-jump"
  termsOfService: "whatever"
  contact: 
    email: "admin@gatejump.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
- url: https://gate-jump.com/api/v0
tags:
- name: "user"
  description: "User interaction API requests"
  externalDocs:
    description: ""
    url: ""
- name: "scopes"
  description: "scopes stuff"
  externalDocs:
    description: ""
    url: ""
- name: "misc"
  description: "Misc API requests"
  externalDocs:
    description: ""
    url: ""
  
paths:
  /:
    get:
      tags:
      - "misc"
      summary: "Check if the server is up and running"
      description: "Should be used as a check to determine if the authentication service is running."
      operationId: "getAlive"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Alive"

  /scope:
    post:
      tags:
      - "scopes"
      summary: "Creates a new scope"
      description: "Scopes are data, more precisely defining how a user can interact with services."
      operationId: "createScope"
      responses:
        200:
          description: Success
          content: {}

  /user:  
    get:
      tags:
      - "user"
      summary: "Get a list of users from the given id."
      description: "Returns a list of users from the given ID with the specified offset and count at a max of 100 each. For administrators only."
      operationId: "getUsers"
      parameters:
      - name: "offset"
        in: "query"
        description: "Starting number of users to enumerate through."
        required: false
        schema:
          type: integer
          format: uint8
      - name: "count"
        in: "query"
        description: "Max amount of users to be returned."
        required: false
        schema:
          type: integer
          format: uint8
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        500:
          description: Invalid Parameters or Database Error
          content: {}
  /register:
    post:
      tags:
      - "user"
      summary: "Register an account to the website."
      description: "thinking"
      operationId: "createUser"
      requestBody:
        description: "No Description"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateData"
      responses:
        200:
          description: Success
          content: {}
  /login:
    post:
      tags:
      - "user"
      summary: "Login an account to the website."
      description: "thinking"
      operationId: "validateUser"
      responses:
        200:
          description: Success
          content: {}
  /refresh:
    post:
      tags:
      - "user"
      summary: "Retrieves a fresh bearer token for a user."
      description: "body inside click"
      operationId: "refreshUser"
      responses:
        200:
          description: Success
          content: {}
  /user/{id}:
    get:
      tags:
      - "user"
      summary: "next to api thingy"
      description: "body inside click"
      operationId: "function name"
      parameters:
      - name: "id"
        in: "path"
        description: "parameter information"
        required: true
        schema:
          type: integer
          format: uint64
      responses:
        200:
          description: Success
          content: {}
    put:
      tags:
      - "user"
      summary: "next to api thingy"
      description: "body inside click"
      operationId: "function name2"
      parameters:
      - name: "id"
        in: "path"
        description: "parameter information"
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Success
          content: {}
    delete:
      tags:
      - "user"
      summary: "next to api thingy"
      description: "body inside click"
      operationId: "function name3"
      parameters:
      - name: "id"
        in: "path"
        description: "parameter information"
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Success
          content: {}
    post:
      tags:
      - "user"
      summary: "next to api thingy"
      description: "body inside click"
      operationId: "function name4"
      parameters:
      - name: "id"
        in: "path"
        description: "parameter information"
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Success
          content: {}
  /user/{name}:
    get:
      tags:
      - "user"
      summary: "next to api thingy"
      description: "body inside click"
      operationId: "function name5"
      parameters:
      - name: "name"
        in: "path"
        description: "parameter information"
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content: {}
  /verify/{magic}:
    get:
      tags:
      - "user"
      summary: "next to api thingy"
      description: "body inside click"
      operationId: "function name6"
      parameters:
      - name: "magic"
        in: "path"
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content: {}

components:
  schemas:
    Blank:
      type: "object"
      xml:
        name: "Blank"
    Alive:
      type: "object"
      properties:
        alive:
          type: boolean
          example: true
      xml:
        name: "Alive"
    User:
      type: "object"
      properties:
        uuid:
          type: "string"
          example: ""
        name:
          type: "string"
          example: "stinkycheeseone890"
        password:
          type: "string"
          format: "password"
          example: "CorrectHorseBatteryStaple"
        email:
          type: "string"
          format: "email"
          example: "iLOVEcheese@gmail.com"
        country:
          type: "string"
          format: "ISO3166-1-Alpha3"
          example: "USA"
        locale:
          type: "string"
          format: "RFC5646"
          example: "en-US"
        date_created:
          type: "string"
          format: "date-time"
        verified:
          type: "boolean"
          example: true
        banned:
          type: "boolean"
          example: false
        last_login:
          type: "string"
          format: "date-time"
        deleted:
          type: "boolean"
          example: false
        date_deleted:
          type: "string"
          format: "date-time"
        
    CreateData:
      type: "object"
      properties:
        name:
          type: "string"
          example: "stinkycheeseone890"
        password:
          type: "string"
          example: "CorrectHorseBatteryStaple"
        email:
          type: "string"
          example: "iLOVEcheese@gmail.com"
      xml:
        name: "UserCreateData"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"