swagger: "2.0"
info:
  description: "This is a reference for gate-jump's API."
  version: "1.0.0"
  title: "gate-jump"
  termsOfService: "whatever"
  contact: 
    email: "admin@gatejump.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "gatejump.com"
basePath: "/"
tags:
- name: "user"
  description: "User interaction API requests"
  externalDocs:
    description: ""
    url: ""
- name: "misc"
  description: "Misc API requests"
  externalDocs:
    description: ""
    url: ""
schemes:
- "https"
- "http"
paths:
  /:
    get:
      tags:
      - "misc"
      summary: "Check if the server is up and running"
      
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"