language: go

go:
- master
- "1.11.x"

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      before_script:
        - brew tap go-task/homebrew-tap
        - brew cask install go-task

    - os: linux
      dist: precise
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - wget
            - pkg-config
      before_script:
        - wget https://github.com/go-task/task/releases/download/v2.2.0/task_linux_amd64.deb
        - sudo dpkg -I task_linux_amd64.deb

script:
  - task build
