language: go

matrix:
    include:
    - os: osx
      osx_image: xcode6.4
      go: "1.11.x"
      env: HOMEBREW_NO_AUTO_UPDATE=1
      addons:
          homebrew:
              taps:
                  - go-task/homebrew-tap
              casks:
                  - go-task
              packages:
                  - go-task
              update: true
    - os: osx
      osx_image: xcode6.4
      go: master
      env: HOMEBREW_NO_AUTO_UPDATE=1
      addons:
          homebrew:
              taps:
                  - go-task/homebrew-tap
              casks:
                  - go-task
              packages:
                  - go-task
              update: true
    - os: linux
      dist: precise
      sudo: required
      go: "1.11.x"
      addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - wget
                  - pkg-config
      before_script:
          - wget https://github.com/go-task/task/releases/download/v2.2.0/task_linux_amd64.deb
          - sudo dpkg -i task_linux_amd64.deb
    - os: linux
      dist: precise
      sudo: required
      go: master
      addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - wget
                  - pkg-config
      before_script:
          - wget https://github.com/go-task/task/releases/download/v2.2.0/task_linux_amd64.deb
          - sudo dpkg -i task_linux_amd64.deb

script:
- task build
