language: go

matrix:
    include:
    - os: osx
      osx_image: xcode6.4
      go: "1.11.x"
      env: HOMEBREW_NO_AUTO_UPDATE=1
      addons:
          homebrew:
              taps:
                  - go-task/homebrew-tap
              casks:
                  - go-task
              packages:
                  - go-task
              update: true
      before_script:
          - go get -u -v github.com/UnnoTed/fileb0x
          - go install github.com/UnnoTed/fileb0x
    - os: osx
      osx_image: xcode6.4
      go: master
      env: HOMEBREW_NO_AUTO_UPDATE=1
      addons:
          homebrew:
              taps:
                  - go-task/homebrew-tap
              casks:
                  - go-task
              packages:
                  - go-task
              update: true
      before_script:
          - go get -u -v github.com/UnnoTed/fileb0x
          - go install github.com/UnnoTed/fileb0x
    - os: linux
      dist: precise
      sudo: required
      go: "1.11.x"
      addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - wget
                  - pkg-config
      before_script:
          - wget https://github.com/go-task/task/releases/download/v2.2.0/task_linux_amd64.deb
          - sudo dpkg -i task_linux_amd64.deb
          - go get -u -v github.com/UnnoTed/fileb0x
          - go install github.com/UnnoTed/fileb0x
    - os: linux
      dist: precise
      sudo: required
      go: master
      addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - wget
                  - pkg-config
      before_script:
          - wget https://github.com/go-task/task/releases/download/v2.2.0/task_linux_amd64.deb
          - sudo dpkg -i task_linux_amd64.deb
          - go get -u -v github.com/UnnoTed/fileb0x
          - go install github.com/UnnoTed/fileb0x

script:
- task build

after_success:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/ee0c1b3ff5b353178248f944f4aaeeff26fb9eb4/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL

after_failure:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/ee0c1b3ff5b353178248f944f4aaeeff26fb9eb4/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL
