pkg = "migrations"
dest = "src/api/migrations"
fmt = false
tags = "" # build tags

[compression]
    compress = false

    # valid values are:
    # -> "NoCompression"
    # -> "BestSpeed"
    # -> "BestCompression"
    # -> "DefaultCompression" or ""
    method = ""

    # do we automatically decompress at runtime, false = decompress at runtime
    keep = false

clean = false
output = "migrate.go"
unexporTed = false
spread = false
lcf = true
debug = false

[[custom]]
    files = ["src/schemas/00001_inital.sql", "src/schemas/00002_meta.sql", "src/schemas/00003_magiclinks.sql", "src/schemas/00004_uuid.sql", "src/schemas/00005_scopes.sql", "src/schemas/00006_groups.sql"]
    base = "src/schemas/"
    prefix = ""
    tags = ""
