// Code generated by fileb0x at "1970-01-01 18:22:31.0331209 -0600 CST m=+0.007001301" from config file "fileb0x.toml" DO NOT EDIT.
// modification hash(d41d8cd98f00b204e9800998ecf8427e)

// This file is only being commited because Travis CI will panic without it

package migrations

func ReadFile(path string) ([]byte, error) {
    return []byte{}, nil
}
